backend:
  name: github
  repo: prairiegiraffe/testing-co
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: https://testing-co-site.pages.dev
display_url: https://testing-co-site.pages.dev

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Services", name: "services", widget: "list"}
      - label: "About"
        name: "about"
        file: "content/about.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "content/contact.yml"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}